### ISSUE TITLE
not working on 10.13.6

### ISSUE THREAD

**Issue by CEHFIDA** [ehrishirajsharma/Swiftness#1]

**Comment by ehrishirajsharma** [comment]
Follow the steps I just mentioned on Readme File: 

1. Download [Sample Built-in Data](https://github.com/ehrishirajsharma/Swiftness/releases/download/V0.2/sample-built-in-data.zip), Unzip and Copy Files (from unzipped folder)
2. Go to `~/Library/Containers/com.RishirajSharma.Swiftness/Data/Documents/` Remove All the files in it
3. Paste the copied files and now open Swiftness App.

Let me know if it doesn't work
